// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"section\"><div class=\"container\"><h1 class=\"title\">SealedUI</h1><div class=\"field\"><label class=\"label\">Scope</label><div class=\"control\"><label class=\"radio\"><input type=\"radio\" name=\"scope\" value=\"cluster\"> Cluster</label> <label class=\"radio\"><input type=\"radio\" name=\"scope\" value=\"namespace\"> Namespace</label> <label class=\"radio\"><input type=\"radio\" name=\"scope\" value=\"strict\"> Strict</label></div></div><div class=\"field\"><label class=\"label\">Namespace</label><div class=\"control\"><input class=\"input\" type=\"text\" placeholder=\"Namespace\" name=\"namespace\"></div></div><div class=\"field\"><label class=\"label\">Secret Name</label><div class=\"control\"><input class=\"input\" type=\"text\" placeholder=\"Secret name\" name=\"secretName\"></div></div><div class=\"field\"><label class=\"label\">Values to Encrypt</label><div class=\"control\"><textarea class=\"textarea\" placeholder=\"MY_TOKEN=SomeSuperSecretToken\nMY_PASSWORD=SomeSuperSecretPassword\"></textarea></div></div><div class=\"field\"><div class=\"control\"><button class=\"button is-link\">Encrypt</button></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout("sealed-secrets-ui").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
